services:
  dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: dvwa
    ports:
      - "8080:80"
    restart: unless-stopped

  s2-005:
    build:
      context: ./labs/s2-005
    container_name: s2-005
    ports:
      - "8081:8080"
    restart: unless-stopped
